import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix KW</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo netflix.png" />
      </Head>
      <div className="overflow-x-hidden">
        {/* Section 1 */}
        <div className="bg-hero-image h-full w-screen border-b-8 border-gray-800">
          <div className="flex flex-col justify-center py-5 bg-black px-3 bg-opacity-70">
            <div className="flex justify-between px-5 lg:px-32 xl:px-60">
              <h1 className="text-[red] font-bold text-2xl lg:text-4xl">
                NETFLIX
              </h1>
              <div className="flex justify-end xl:h-7">
                <select className="md:hidden mr-3 px-2 py-1 rounded-sm bg-transparent border text-white text-xs">
                  <option value="">&#127760;</option>
                  <option className="text-black" value="ID">
                    ID
                  </option>
                  <option className="text-black" value="EN">
                    EN
                  </option>
                </select>
                <select className="hidden md:flex mr-3 px-2 py-1 rounded-sm bg-transparent border text-white text-xs">
                  <option className="text-black" value="ID">
                    &#127760; Bahasa Indonesia
                  </option>
                  <option className="text-black" value="EN">
                    &#127760; English
                  </option>
                </select>
                <button
                  type="button"
                  className="text-white text-sm px-2 py-1 bg-[red] rounded-sm"
                >
                  Masuk
                </button>
              </div>
            </div>
            <div className="text-white text-center mt-12 md:mt-32 lg:mt-60 lg:mb-32 xl:mt-36 md:mb-10">
              <h1 className="font-bold text-3xl mx-12 md:mx-12 lg:text-5xl lg:mx-32 ">
                Film, acara TV tak terbatas, dan lebih banyak lagi.
              </h1>
              <h2 className="my-5 lg:text-xl">
                Tonton di mana pun. Batalkan kapan pun.
              </h2>
              <h3 className="mx-14 md:mx-32 mb-3">
                Siap menonton? masukkan email untuk membuat atau memulai lagi
                keanggotaanmu.
              </h3>
              <div className="flex flex-col md:flex-row items-center justify-center mx-8 md:m-auto md:w-[500px]">
                <input
                  type="text"
                  placeholder="Alamat email"
                  className="w-3/4 rounded-sm px-3 py-2 text-sm h-10 md:h-12"
                />
                <button
                  type="button"
                  className="mt-3 md:mt-0 text-md bg-[red] px-4 py-2 rounded-sm font-bold h-10 md:h-12"
                >
                  {`Mulai >`}{' '}
                </button>
              </div>
            </div>
          </div>
        </div>
        {/* Section 2 */}
        <div className="bg-black h-full w-screen border-b-8 border-gray-800">
          <div className="flex flex-col py-5 lg:flex-row lg:py-20 justify-center items-center bg-black h-full bg-opacity-70">
            <div className="text-white text-center lg:w-1/3">
              <h1 className="font-bold text-3xl lg:text-[2.5rem] lg:text-left">
                Nikmati di TV-mu.
              </h1>
              <h2 className="mt-3 px-12 md:px-24 lg:text-left lg:px-0 lg:text-lg lg:pr-20">
                Tonton di Smart TV, Playstation, Xbox, Chromecast, Apple TV,
                pemutar Blu-ray, dan banyak lagi.
              </h2>
            </div>
            <Image
              src={`/logo tv.png`}
              width={450}
              height={400}
              alt="logo tv"
              className="w-[90%] lg:w-[30%]"
            />
          </div>
        </div>
        {/* Section 3 */}
        <div className="bg-black h-full md:w-screen border-b-8 border-gray-800">
          <div className="flex flex-col py-5 lg:flex-row-reverse pt-10 justify-center items-center bg-black h-full bg-opacity-70 ">
            <div className="text-white text-center lg:w-1/2">
              <h1 className="font-bold text-3xl md:mx-10 lg:text-[2.5rem] lg:text-left lg:mx-0 lg:pr-[17rem] leading-normal">
                Download acara TV untuk menontonnya secara offline.
              </h1>
              <h2 className="mt-3 px-12 lg:px-0 lg:text-left lg:text-xl lg:pr-64">
                Simpan favoritmu dengan mudah agar selalu ada acara TV dan film
                yang bisa ditonton.
              </h2>
            </div>
            <div className="lg:ml-32 lg:w-1/3 lg:mt-12">
              <Image
                src={`/logo mobile.jpg`}
                width={450}
                height={450}
                alt="logo tv"
                className="w-full"
              />
              <div className="flex items-center justify-between relative -top-24 bg-black  border-2 border-gray-800 w-[60%] m-auto text-left p-2 rounded-lg">
                <div className="flex">
                  <Image
                    src="/stranger things.png"
                    width={30}
                    height={70}
                    alt="mendownload"
                  />
                  <div className="pl-3">
                    <h3 className="text-white font-bold text-sm ">
                      Stranger Things
                    </h3>
                    <p className="text-blue-500 text-xs">Men-download...</p>
                  </div>
                </div>
                <p className="text-2xl">&#128640;</p>
              </div>
            </div>
          </div>
        </div>
        {/* Section 4 */}
        <div className="bg-black h-full w-screen border-b-8 border-gray-800">
          <div className="flex flex-col py-5 lg:flex-row justify-center items-center bg-black h-full bg-opacity-70 lg:py-20">
            <div className="text-white text-center lg:text-left lg:w-1/3 pb-5">
              <h1 className="font-bold text-3xl lg:text-5xl">
                Tonton di mana pun.
              </h1>
              <h2 className="mt-3 px-12 lg:px-0 lg:text-xl">
                Streaming film dan acara TV tak terbatas di ponsel, tablet,
                laptop, dan TV-mu.
              </h2>
            </div>
            <Image
              src={`/logo device.png`}
              width={450}
              height={450}
              alt="logo tv"
              className="md:w-[80%] lg:w-[35%]"
            />
          </div>
        </div>
        {/* Section 5 */}
        <div className="bg-black h-full w-screen border-b-8 border-gray-800">
          <div className="flex flex-col py-5 lg:flex-row-reverse justify-center items-center lg:py-20  bg-black h-full bg-opacity-70">
            <div className="text-white text-center pb-5 lg:text-left lg:w-1/3">
              <h1 className="font-bold text-3xl lg:text-5xl">
                Buat profil untuk anak.
              </h1>
              <h2 className="mt-3 px-10 md:px-16 lg:px-0 lg:text-xl">
                Kirim anak-anak untuk bertualang bersama karakter favorit mereka
                di dunia yang dibuat khusus untuk mereka—gratis dengan
                keanggotaanmu.
              </h2>
            </div>
            <Image
              src={`/child.png`}
              width={450}
              height={450}
              alt="logo tv"
              className="md:w-[80%] lg:w-[30%]"
            />
          </div>
        </div>
        {/* Section 6 */}
        <div className="bg-black pb-10 w-screen py-5 h-full border-b-8 border-gray-800 text-white lg:px-32 xl:px-80">
          <h1 className="font-bold text-3xl text-center pb-5">
            Tanya Jawab Umum
          </h1>
          <div className="flex flex-col text-xl w-full">
            {/* QA 1 */}
            <div className="mb-2 w-full">
              <button
                type="button"
                className="flex w-full px-3 justify-between items-center bg-gray-800 mb-1 pl-5 h-16 text-left "
                onClick={() => {
                  const toggleQA1 = document.getElementById('toggleQA1');
                  const textQA1 = document.getElementById('textQA1');
                  toggleQA1.classList.toggle('rotate-[135deg]');
                  textQA1.classList.toggle('max-h-0');
                  textQA1.classList.toggle('max-h-96');
                  textQA1.classList.toggle('py-0');
                  textQA1.classList.toggle('py-3');
                }}
              >
                Apa itu Netflix?
                <span
                  className="pr-5 transition-all duration-300 ease-in-out origin-[25%_50%]"
                  id="toggleQA1"
                >
                  &#10010;
                </span>
              </button>
              <div
                className="overflow-hidden max-h-0 py-0 bg-gray-800 px-3 text-left transition-all duration-300 rotate-
              ease-in-out"
                id="textQA1"
              >
                <p>
                  Netflix adalah layanan streaming yang menawarkan berbagai
                  acara TV pemenang penghargaan, film, anime, dokumenter, dan
                  banyak lagi di ribuan perangkat yang terhubung ke Internet.
                  Kamu bisa menonton sepuasnya, kapan pun kamu mau, tanpa satu
                  iklan pun – semuanya dengan satu harga bulanan yang murah.
                  Selalu ada tontonan baru dan acara TV serta film baru yang
                  ditambahkan setiap minggu!
                </p>
              </div>
            </div>
            {/* QA 2 */}
            <div className="mb-2 w-full">
              {' '}
              <button
                type="button"
                className="flex w-full px-3 justify-between items-center bg-gray-800 mb-1 pl-5 h-16 text-left "
                onClick={() => {
                  const toggleQA2 = document.getElementById('toggleQA2');
                  const textQA2 = document.getElementById('textQA2');
                  toggleQA2.classList.toggle('rotate-[135deg]');
                  textQA2.classList.toggle('max-h-0');
                  textQA2.classList.toggle('max-h-96');
                  textQA2.classList.toggle('py-0');
                  textQA2.classList.toggle('py-3');
                }}
              >
                Berapa biaya berlangganan Netflix?{' '}
                <span
                  className="pr-5 transition-all duration-300 ease-in-out origin-[25%_50%]"
                  id="toggleQA2"
                >
                  &#10010;
                </span>
              </button>
              <div
                className="overflow-hidden max-h-0 py-0 bg-gray-800 px-3 w-full text-left transition-all duration-300 rotate-
               ease-in-out"
                id="textQA2"
              >
                <p>
                  Tonton Netflix di smartphone, tablet, Smart TV, laptop, atau
                  perangkat streaming-mu, semuanya dengan satu harga bulanan
                  tetap Rentang harga mulai dari Rp54.000 hingga Rp186.000 per
                  bulan. Tanpa biaya ekstra, tanpa kontrak.
                </p>
              </div>
            </div>
            {/* QA 3 */}
            <div className="mb-2 w-full">
              {' '}
              <button
                type="button"
                className="flex justify-between items-center bg-gray-800 mb-1 pl-5 w-full px-3 h-16 text-left "
                onClick={() => {
                  const toggleQA3 = document.getElementById('toggleQA3');
                  const textQA3 = document.getElementById('textQA3');
                  toggleQA3.classList.toggle('rotate-[135deg]');
                  textQA3.classList.toggle('max-h-0');
                  textQA3.classList.toggle('max-h-96');
                  textQA3.classList.toggle('py-0');
                  textQA3.classList.toggle('py-3');
                }}
              >
                Di mana saya bisa menonton?{' '}
                <span
                  className="pr-5 transition-all duration-300 ease-in-out origin-[25%_50%]"
                  id="toggleQA3"
                >
                  &#10010;
                </span>
              </button>
              <div
                className="overflow-hidden max-h-0 py-0 bg-gray-800 px-3 w-full text-left transition-all duration-300 rotate-
                ease-in-out"
                id="textQA3"
              >
                <p>
                  Tonton di mana pun, kapan pun. Masuk ke akun Netflix-mu untuk
                  menonton langsung di netflix.com dari komputer pribadi atau di
                  perangkat yang terhubung ke Internet dan mendukung aplikasi
                  Netflix, termasuk smart TV, smartphone, tablet, pemutar media
                  streaming, dan konsol game. Kamu juga bisa men-download acara
                  favoritmu dengan aplikasi iOS, Android, atau Windows 10.
                  Gunakan download untuk menonton saat kamu di perjalanan dan
                  tidak punya koneksi Internet. Bawa Netflix ke mana saja.
                </p>
              </div>
            </div>
            {/* QA 4 */}
            <div className="mb-2 w-full">
              {' '}
              <button
                type="button"
                className="flex justify-between items-center bg-gray-800 mb-1 pl-5 w-full px-3 h-16 text-left "
                onClick={() => {
                  const toggleQA4 = document.getElementById('toggleQA4');
                  const textQA4 = document.getElementById('textQA4');
                  toggleQA4.classList.toggle('rotate-[135deg]');
                  textQA4.classList.toggle('max-h-0');
                  textQA4.classList.toggle('max-h-96');
                  textQA4.classList.toggle('py-0');
                  textQA4.classList.toggle('py-3');
                }}
              >
                Bagaimana cara membatalkannya?{' '}
                <span
                  className="pr-5 transition-all duration-300 ease-in-out origin-[25%_50%]"
                  id="toggleQA4"
                >
                  &#10010;
                </span>
              </button>
              <div
                className="overflow-hidden max-h-0 py-0 bg-gray-800 px-3 w-full text-left transition-all duration-300 rotate-
                ease-in-out"
                id="textQA4"
              >
                <p>
                  Netflix fleksibel. Tanpa kontrak menyebalkan dan tanpa
                  komitmen. Kamu dapat dengan mudah membatalkan akunmu secara
                  online dengan dua kali klik. Tanpa biaya pembatalan – mulai
                  atau hentikan akunmu kapan pun.
                </p>
              </div>
            </div>
            {/* QA 5 */}
            <div className="mb-2 w-full">
              {' '}
              <button
                type="button"
                className="flex justify-between items-center bg-gray-800 mb-1 pl-5 w-full px-3 h-16 text-left "
                onClick={() => {
                  const toggleQA5 = document.getElementById('toggleQA5');
                  const textQA5 = document.getElementById('textQA5');
                  toggleQA5.classList.toggle('rotate-[135deg]');
                  textQA5.classList.toggle('max-h-0');
                  textQA5.classList.toggle('max-h-96');
                  textQA5.classList.toggle('py-0');
                  textQA5.classList.toggle('py-3');
                }}
              >
                Apakah yang bisa ditonton di Netflix?{' '}
                <span
                  className="pr-5 transition-all duration-300 ease-in-out origin-[25%_50%]"
                  id="toggleQA5"
                >
                  &#10010;
                </span>
              </button>
              <div
                className="overflow-hidden max-h-0 py-0 bg-gray-800 px-3 w-full text-left transition-all duration-300 rotate-
                ease-in-out"
                id="textQA5"
              >
                <p>
                  Netflix memiliki pustaka lengkap yang berisi film panjang,
                  film dokumenter, acara TV, anime, Netflix original pemenang
                  penghargaan, dan lebih banyak lagi. Tonton sepuasnya, kapan
                  pun kamu mau.
                </p>
              </div>
            </div>
            {/* QA 6 */}
            <div className="mb-2 w-full">
              {' '}
              <button
                type="button"
                className="flex justify-between items-center bg-gray-800 mb-1 pl-5 w-full px-3 h-16 text-left "
                onClick={() => {
                  const toggleQA6 = document.getElementById('toggleQA6');
                  const textQA6 = document.getElementById('textQA6');
                  toggleQA6.classList.toggle('rotate-[135deg]');
                  textQA6.classList.toggle('max-h-0');
                  textQA6.classList.toggle('max-h-96');
                  textQA6.classList.toggle('py-0');
                  textQA6.classList.toggle('py-3');
                }}
              >
                Apakah Nextflix sesuai bagi anak-anak?{' '}
                <span
                  className="pr-5 transition-all duration-300 ease-in-out origin-[25%_50%]"
                  id="toggleQA6"
                >
                  &#10010;
                </span>
              </button>
              <div
                className="overflow-hidden max-h-0 py-0 bg-gray-800 px-3 w-full text-left transition-all duration-300 rotate-
                ease-in-out"
                id="textQA6"
              >
                <p>
                  Pengalaman Netflix Anak disertakan dalam keanggotaan agar kamu
                  punya kontrol orang tua saat anak-anak menikmati acara TV dan
                  film untuk keluarga di rumah. Profil anak dilengkapi kontrol
                  orang tua yang dilindungi PIN sehingga kamu bisa membatasi
                  rating usia konten yang bisa ditonton anak dan memblokir judul
                  tertentu yang tidak boleh ditonton anak-anak.
                </p>
              </div>
            </div>
            <h3 className="px-16 md:px-28 mb-3 text-base text-center mt-10 lg:text-xl">
              Siap menonton? masukkan email untuk membuat atau memulai lagi
              keanggotaanmu.
            </h3>
            <div className="flex justify-center flex-col md:flex-row items-center md:m-auto md:w-[500px]">
              <input
                type="text"
                placeholder="Alamat email"
                className="w-3/4 rounded-sm px-3 py-2 text-sm h-12"
              />
              <button
                type="button"
                className="mt-3 md:mt-0 text-md bg-[red] px-4 py-2 rounded-sm font-bold h-12"
              >
                {`Mulai >`}{' '}
              </button>
            </div>
          </div>
        </div>
        <footer className="bg-black  w-screen text-gray-300 text-sm p-5">
          <p>
            Ada pertanyaan? Hubungi{' '}
            <span className="underline">007-803-321-2148</span>
          </p>
          <div className="mt-5 h-full w-full">
            <ul className="grid grid-cols-2 md:grid-cols-4 underline lg:grid-cols-3 xl:grid-cols-4 mr-14 gap-3">
              <li>Tanya Jawab</li>
              <li>Pusat Bantuan</li>
              <li>Pusat Media</li>
              <li>Lowongan Kerja</li>
              <li>Beli Kartu Hadiah</li>
              <li>Ketentuan Penggunaan</li>
              <li>Preferensi Cookie</li>
              <li>Hubungi Kami</li>
              <li>Informasi Legal</li>
              <li>Ketentuan Kartu Hadiah</li>
              <li>Akun</li>
              <li>Hubungan Investor</li>
              <li>Tukar Kartu Hadiah</li>
              <li>Cara Menonton</li>
              <li>Privasi</li>
              <li>Informasi Perusahaan</li>
              <li>Uji Kecepatan</li>
              <li>Hanya di Netflix</li>
            </ul>
          </div>
          <select className="mt-5 mr-3 px-2 py-1 rounded-sm bg-transparent border text-white text-md text-left">
            <option className="text-black" value="Bahasa Indonesia">
              &#127760; Bahasa Indonesia
            </option>
            <option className="text-black" value="English">
              &#127760; English
            </option>
          </select>
          <p className="mt-5">Netflix Indonesia</p>
        </footer>
      </div>
    </>
  );
}
